* Sect1
* Sect2
* Sect3
* Sect4
* Sect5
* Sect6
* Sect7
* Sect8
* Sect9
* Sect10
* Sect11
* Sect12
* Sect13
* Sect14
* Sect15
* Sect16
* Sect17
* Sect18
* Sect19
* Sect20
* Sect21
* Sect22
Links
+ https://github.com/TaylorMonacelli/pandoc-practice/blob/master/t8.md
+ https://gitlab.com/mtm/pandoc-practice/blob/master/t8.md

* Sect23

<<myanchor>>

* Sect24
* Sect25
* <<myanchor1>> Sect26
* Sect27
* Sect28
* Sect29
* Sect30
* Sect31
* Sect32
* Sect33
* Sect34
* Sect35
* Sect36
* Sect37
* Sect38
* Sect39
* Sect40
* Sect41
* Sect42
* Sect43
* Sect44
* Sect45
* Sect46
+ [[file:t8.org][mytest]]
+ [[file:t8.org::sect42]]

+ This works in org-mode, but not in webui [[file:t8.org::Sect42]]

* Sect47
* Sect48
* Sect49
* Sect50

+ This doesn't work in emacs org-mode linking, but works in webui links.
#+BEGIN_SRC
[[#sect22][link to section 22]]
#+END_SRC
which creates this: [[#sect22][link to section 22]]

but this has a problem.  Emacs org-mode linking doesnt work here.

+ This doesn't work in emacs org-mode linking, but works in webui links.
#+BEGIN_SRC
[[file:t8.md#sect22][link to section 22]]
#+END_SRC
which creates this: [[file:t8.md#sect22][link to section 22]]

This has a problem.  The output file is t8.md, but the source file is
t8.org so you've broken emacs org-mode linking in an effort to get web
linking working.

+ This doesn't work in emacs org-mode linking or webui links.
#+BEGIN_SRC
[[t8.md#sect22][link to section 22]]
#+END_SRC
which creates this: [[t8.md#sect22][link to section 22]]

+ This doesn't work:
#+BEGIN_SRC
[[file:t8.md#Sect22][link to section 22]]
#+END_SRC
which creates this: [[file:t8.md#Sect22][link to section 22]]

+ This doesn't work
#+BEGIN_SRC
<<myanchor>> along with [[file:t8.md#myanchor][link to my anchor]]
#+END_SRC
which creates this: [[file:t8.md#myanchor][link to my anchor]]

+ This doesn't work
#+BEGIN_SRC
<<myanchor>> along with [[#myanchor][link to my anchor]]
#+END_SRC
which creates this: [[#myanchor][link to my anchor]]

+ This is crappy to link from t8.md to t8.org.  Don't switch files.
#+BEGIN_SRC
[[file:t8.org#sect22][link to section 22]]
#+END_SRC
which creates this: [[file:t8.org#sect22][link to section 22]]

+ This works in emacs, but not in webui.
#+BEGIN_SRC
<<myanchor>> along with [[myanchor][link to my anchor]]
#+END_SRC
which creates this: [[myanchor][link to my anchor]]

+ Works in emacs, but not in webui
#+BEGIN_SRC
<<myanchor1>> along with [[myanchor1][link to my anchor1]]
#+END_SRC
which creates this: [[myanchor1][link to my anchor1]]

+ Doesn't work in emacs org-mode or in webui
#+BEGIN_SRC
<<myanchor>> along with [[file:t8.org::#myanchor]]
#+END_SRC
which creates this: [[file:t8.org::#myanchor]]

+ Doesn't work in emacs org-mode or in webui
#+BEGIN_SRC
<<myanchor>> along with [[file:./t8.org::#myanchor]]
#+END_SRC
which creates this: [[file:./t8.org::#myanchor]]

So, in summary, I don't know how to write org-mode syntax such that
pandoc output will generate linkable markdown and still have emacs
org-mode links still work
+ must have file: prefix
+ drawback: even though you're documenting in t8.org, you must link to
  the target
#+BEGIN_SRC
[[file:t8.org#sect22][link to section 22]] # instead of this
[[file:t8.md#sect22][link to section 22]]  # you must use this
#+END_SRC
+ must have lowercase section name.  Instead of =file:t8.md#Sect22=, use
  =file:t8.md#sect22=
+ you can only link to sections within the document, you cant create
